name: CD to Local Kubernetes
on:
  workflow_run:
    workflows: ["CI"]  # שם זה צריך להתאים לשם של ה-CI workflow שלך
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # זה הקו החשוב - זה אומר להשתמש ב-runner המקומי
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # רץ רק אם ה-CI הצליח

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f weather-app-deployment.yaml --validate=false
          kubectl apply -f weather-app-service.yaml --validate=false
          
      - name: Check deployment status
        run: |
          kubectl rollout status deployment/weather-app
          kubectl get pods -l app=weather-app
          kubectl get service weather-app-service

      - name: Print service URL
        run: |
          echo "Service exposed on NodePort: $(kubectl get service weather-app-service -o jsonpath='{.spec.ports[0].nodePort}')"
