name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Apply Kubernetes deployment
        run: |
          # Apply the deployment and service files
          kubectl apply -f weather-app-deployment.yaml
          kubectl apply -f weather-app-service.yaml

      - name: Check deployment status
        run: |
          kubectl rollout status deployment/weather-app
