name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Verify cluster connection
        run: |
          kubectl config set-cluster docker-desktop --insecure-skip-tls-verify=true
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f weather-app-deployment.yaml --validate=false
          kubectl apply -f weather-app-service.yaml --validate=false
          
      - name: Check deployment status
        run: |
          kubectl rollout status deployment/weather-app
          kubectl get pods -l app=weather-app
          kubectl get service weather-app-service

      - name: Print service URL
        run: |
          echo "Service exposed on NodePort: $(kubectl get service weather-app-service -o jsonpath='{.spec.ports[0].nodePort}')"
